
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/JoakinRoa151/microservices-data-project.git
  application:
    name: config-service